export const characterClasses = [
    {
      name: 'Guerreiro',
      description: 'Ótimo lutador, ataca com força bruta.',
      icon: '⚔️',
      color: 'text-blood-red',
      attackType: 'vermelho',
      heroes: ['Floid', 'Devon', 'Abrana'],
      goldTarget: 20000,
      gifUrl: './assets/characters/guerreiro.gif',
    },
    {
      name: 'Elfo',
      description: 'Ágil e rápido, mestre em encontrar passagens.',
      icon: '🏹',
      color: 'text-stone-light',
      attackType: 'branco',
      heroes: ['Alonzo', 'Kasira', 'Longbranch'],
      goldTarget: 10000,
      gifUrl: './assets/characters/elfo.gif',
    },
    {
      name: 'Anão',
      description: 'Robusto e resistente, mas lento.',
      icon: '🔨',
      color: 'text-arcane-blue',
      attackType: 'azul',
      heroes: ['Pricilla', 'Thugg', 'Kador'],
      goldTarget: 10000,
      gifUrl: './assets/characters/anao.gif',
    },
    {
      name: 'Feiticeiro',
      description: 'Poderoso com magias, mas frágil em combate.',
      icon: '🔮',
      color: 'text-void-purple',
      attackType: 'verde',
      heroes: ['Nook', 'Flind', 'Rast'],
      goldTarget: 30000,
      gifUrl: './assets/characters/feiticeiro.gif',
    },
    {
      name: 'Paladino',
      description: 'Guerreiro sagrado com o poder da cura.',
      icon: '🛡️',
      color: 'text-ethereal-blue',
      attackType: 'vermelho',
      heroes: ['Keenya', 'Flennetar', 'Madelyne'],
      goldTarget: 30000,
      gifUrl: './assets/characters/paladino.gif',
    },
    {
      name: 'Ladrão',
      description: 'Especialista em emboscadas e ataques em grupo.',
      icon: '🗡️',
      color: 'text-green-500',
      attackType: 'verde',
      heroes: ['Zinda', 'Thosia', 'Krind'],
      goldTarget: 20000,
      gifUrl: './assets/characters/ladrao.gif',
    }
];